services:
  frontend:
    build:
      context: ./frontend
      dockerfile: DockerfileFrontendRECUA
    container_name: frontendACM
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true # Activa polling para asegurar detección de cambios en Docker
    depends_on:
      - backend
    networks:
      - redwebRECUA

  backend:
    build:
      context: ./backend
      dockerfile: DockerfileBackendRECUA
    container_name: backendACM
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - database
    command: >
      sh -c "
      composer install &&
      composer show doctrine/dbal &&
      php -S 0.0.0.0:8000 -t public"
    networks:
      - redwebRECUA

  database:
    container_name: databaseACM
    image: mysql:8.0
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - database_data:/var/lib/mysql
    networks:
      - redwebRECUA

  phpmyadmin:
    container_name: phpmyadminACM
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: database
      PMA_USER: user
      PMA_PASSWORD: password
    depends_on:
      - database
    networks:
      - redwebRECUA

  web:
    build:
      context: ./web
      dockerfile: DockerfileWebRECUA
    container_name: webACM
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./web/certs:/etc/nginx/certs
    depends_on:
      - frontend
      - backend
    networks:
      - redwebRECUA

networks:
  redwebRECUA:
    driver: bridge

volumes:
  database_data: